SamsC.02.05.c required modification to compile
in the orriginal script found on page 35 of the text, 
line 9: fgets (buffer );
returned an error message: SamsC.02.05.c: In function ‘main’:
SamsC.02.05.c:9:5: error: too few arguments to function ‘fgets’
     fgets( buffer );
     ^~~~~
In file included from SamsC.02.05.c:2:0:
/usr/include/stdio.h:624:14: note: declared here
 extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)
              ^~~~~
therefore, the line had to be changed to:
fgets(buffer, sizeof buffer, stdin); 

this correction was provided at StackOverflow.com